# Site settings
title: Zedrick John Villas
description: Homepage
# baseurl: "/particle" # the subpath of your site, e.g. /blog
# url: "localhost:3000" # the base hostname & protocol for your site e.g. http://willianjusten.com.br

# User settings
username: Zedrick John Villas
user_description: I have 6 years of experience in web development. I have been a front-end developer who converts design submitted by the client into a responsive web page using the most appropriate technology for the design. I have also been a back-end developer who converts business requirements into working system functions or features using the most efficient and effective tools to meet the established requirements. I am an achiever and goal-oriented person who is keen to details and would like to keep everything in a systematic manner.
user_title: Web Developer
email: zedrickvillas@gmail.com
twitter_username: zedrickvillas
linkedin_username: zedrickvillas
facebook_username: zjvillas

# Google-analytics
google-analytics:
  id: ""

exclude: ['package.json', 'src' , 'node_modules']
