# Site settings
title: Zedrick John Villas
description: My public portfolio containing a brief description of my experience in the IT industry, the technologies that i have used, and projects delivered.
# baseurl: "/particle" # the subpath of your site, e.g. /blog
# url: "localhost:3000" # the base hostname & protocol for your site e.g. http://willianjusten.com.br

# User settings
username: Zedrick John Villas
user_description: An outstanding IT Professional who have been in the IT industry for 6 years, with experience in the digital banking, enterprise architecture, e-commerce, and web & mobile development. Managed multiple agile teams who delivered quality products accompanied by precise and transparent reports.
user_title: IT Professional, MIT, PSM™
email: zedrickvillas@gmail.com
twitter_username: zedrickvillas
linkedin_username: zedrickvillas
facebook_username: zedrickvillas

# Google-analytics
google-analytics:
  id: "UA-122300369-1"

exclude: ['package.json', 'src' , 'node_modules']
