# Site settings
title: Zedrick John Villas
description: Homepage
# baseurl: "/particle" # the subpath of your site, e.g. /blog
# url: "localhost:3000" # the base hostname & protocol for your site e.g. http://willianjusten.com.br

# User settings
username: Zedrick John Villas
user_description: I have 6 years of experience in web development.I have been a front-end developer which converts design submitted by the client into a responsive web page using the most appropriate technology for their requirements. and back-end developer; An achiever and goal-oriented person.
user_title: Web Developer
email: zedrickvillas@gmail.com
twitter_username: zedrickvillas
linkedin_username: zedrickvillas
facebook_username: zjvillas

# Google-analytics
google-analytics:
  id: ""

exclude: ['package.json', 'src' , 'node_modules']
