# Site settings
title: Zedrick John Villas
description: My public portfolio containing a brief description of my experience in the IT industry, the technologies that i have used, and projects delivered.
# baseurl: "/particle" # the subpath of your site, e.g. /blog
# url: "localhost:3000" # the base hostname & protocol for your site e.g. http://willianjusten.com.br

# User settings
username: Zedrick John Villas
user_description: An outstanding IT Professional who has been in the IT industry for almost a decade, with experience in digital banking, enterprise architecture, e-commerce, and web & mobile development. He managed multiple agile teams that delivered quality products accompanied by precise and transparent reports.
user_title: MIT, PSM™, PSPO™, PSK™
email: zedrickvillas+portfolio@gmail.com
twitter_username: zedrickvillas?ref=portfolio
linkedin_username: zedrickvillas?ref=portfolio
facebook_username: zedrickvillas?ref=portfolio

# Google-analytics
google-analytics:
  id: "UA-122300369-1"

exclude: ['package.json', 'src' , 'node_modules']
